SELECT TOP (1000) [Id]
      ,[Descricao]
      ,[DataEntrega]
      ,[NivelSurtos]
      ,[QtdHoras]
      ,[QtdErros]
      ,[Aprendizado]
      ,[HorasDeSono]
      ,[Folga]
  FROM [projAula06062024].[dbo].[OportunidadeModel]
