// <auto-generated />
using System;
using APIOPortunidade.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIOPortunidade.Migrations
{
    [DbContext(typeof(APIOPortunidadeContext))]
    [Migration("20240607014012_InitialCreated")]
    partial class InitialCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Oportunidade.OportunidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Aprendizado")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Folga")
                        .HasColumnType("int");

                    b.Property<long>("HorasDeSono")
                        .HasColumnType("bigint");

                    b.Property<string>("NivelSurtos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("QtdErros")
                        .HasColumnType("bigint");

                    b.Property<int>("QtdHoras")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OportunidadeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
